[Arch-Install-scripts]
ArchInstall = "scripts/archinstall.sh"

[Debian-Specfic-Scripts]
DebianInstall = "scripts/debianinstall.sh"

[Seedbox-Scripts]
Seedbox-All = "scripts/seedboxall.sh"
Docker-Seedbox = "scripts/dockerseedbox.sh"

[Development]
Git = "scripts/git.sh"

[AI]
AI-Dependancies = "scripts/aidependancies.sh"
Ollama = "scripts/ollama.sh"
Flux = "scripts/flux.sh"

[Multimedia]
VLC = "vlc.sh"
GIMP = "gimp.sh"
Audacity = "audacity.sh"

[Utilities]
htop = "htop.sh"
neofetch = "neofetch.sh"
tmux = "tmux.sh"

[Communication]
Discord = "discord.sh"
Slack = "slack.sh"
Zoom = "zoom.sh"

[Gaming]
GamingDependancies = "scripts/gamingdeps.sh"
Steam = "scripts/steam.sh"
Lutris = "scripts/lutris.sh"

