[Arch-Install-scripts]
ArchInstall = "scripts/archinstall.sh"
Arch-Postinstall-Goodies = "scripts/postinstall2.sh"
Enable-ssh-server = "scripts/arch-openssh.sh"
Install-Virt-Manager = "scripts/arch-installvirt.sh"

[Debian-Specfic-Scripts]
DebianInstall = "scripts/debianinstall.sh"
Restreamer = "scripts/deb-restreamer-install.sh"

[Seedbox-Scripts]
Seedbox-All = "scripts/seedboxall.sh"
Docker-Seedbox = "scripts/docker-media.sh"

[Desktop-Environment]
Hyprland = "scripts/hyprlandinstall.sh" #Needs to be tested
Cosmic = "scripts/installcosmic.sh" #Needs to be tested
Gnome = "scripts/gnomeinstall.sh" #Needs to be tested
Budgie = "scripts/budgieinstall.sh" #Needs to be tested
Cinnamon = "scripts/cinnamoninstall.sh" #Needs to be tested
KDE = "scripts/kdeinstall.sh" #Needs to be tested

[Development]
Git = "scripts/git.sh"
Build-Utils = "scripts/build-utils.sh"

[AI]
AI-Dependancies = "scripts/aidependancies.sh"
Ollama = "scripts/ollamasetup.sh"
Flux = "scripts/fluxinstall.sh"

[Multimedia]
VLC = "vlc.sh"
GIMP = "gimp.sh"
Audacity = "audacity.sh"

[Utilities]
htop = "htop.sh"
neofetch = "neofetch.sh"
tmux = "tmux.sh"
bash-prompt = "scripts/bashprompt.sh"
general-utils = "scripts/utils.sh"

[Communication]
Discord = "discord.sh"
Slack = "slack.sh"
Zoom = "zoom.sh"

[Gaming]
GamingDependancies = "scripts/gamingdeps.sh"
Steam = "scripts/steam.sh"
Lutris = "scripts/lutris.sh"

