[Arch-Install-scripts]
ArchInstall = "scripts/archinstall.sh"

[Development]
Git = "scripts/git.sh"

[Multimedia]
VLC = "vlc.sh"
GIMP = "gimp.sh"
Audacity = "audacity.sh"

[Utilities]
htop = "htop.sh"
neofetch = "neofetch.sh"
tmux = "tmux.sh"

[Communication]
Discord = "discord.sh"
Slack = "slack.sh"
Zoom = "zoom.sh"

[Gaming]
GamingDependancies = "scripts/gamingdeps.sh"
Steam = "scripts/steam.sh"
Lutris = "scripts/lutris.sh"

