#!/bin/bash

# @Tech Logicals

set -eu

function make_install {
  local archive
  local contents=(
    ./functions/00-check
    ./functions/00-install
    ./hooks
    ./install
    ./packages/install.list
    ./utils/sdboot-mkconfig
  )
  pushd "$(git rev-parse --show-toplevel)" > /dev/null
  archive="$(tar -cz -O "${contents[@]}" | base64 -w 0)"
  cat << EOF
#!/bin/bash
set -Eeu

echo "Running unified Arch Linux 'install' script ($(git rev-parse HEAD))."
TMP="\$(mktemp -d)"
trap 'rm -rf "\${TMP}"; exit' INT TERM ERR EXIT
cd "\${TMP}"
tar -m -xzf <(base64 -d <<< ${archive})
./install
EOF
  popd > /dev/null
}

function make_postinstall {
  local archive
  local contents=(
    ./configs
    ./daemons
    ./dconf
    ./dotfiles
    ./functions/00-check
    ./functions/01-base
    ./functions/01-misc
    ./functions/02-desktop
    ./functions/03-network
    ./functions/03-packages
    ./functions/04-themes
    ./functions/05-personal
    ./packages
    ./postinstall
  )
  pushd "$(git rev-parse --show-toplevel)" > /dev/null
  archive="$(tar -cz -O "${contents[@]}" | base64 -w 0)"
  cat << EOF
#!/bin/bash

#set -Eeu

echo "Running unified Arch Linux 'postinstall' script ($(git rev-parse HEAD))."
TMP="\$(mktemp -d)"
trap 'rm -rf "\${TMP}"; exit' INT TERM ERR EXIT
cd "\${TMP}"
tar -m -xzf <(base64 -d <<< ${archive})
./postinstall
EOF
  popd > /dev/null
}

MODE="${1:-both}"

case "${MODE}" in
  both)
    for MODE in install postinstall; do
      make_"${MODE}" > archlinux_"${MODE}"
      chmod +x archlinux_"${MODE}"
    done
    ;;
  install | postinstall)
    make_"${MODE}" > archlinux_"${MODE}"
    chmod +x archlinux_"${MODE}"
    ;;
  *)
    echo "ERROR: ${MODE@Q} not supported. Exiting."
    exit 3
    ;;
esac
